services:

  gatling-runner:
    container_name: gatling-runner
    image: maven:3.9-eclipse-temurin-20
    working_dir: /code
    volumes:
      - .:/code
      - ~/.m2:/root/.m2
    command: mvn gatling:test -Dgatling.simulationClass=it.zerko.simulation.F1FantasyToolsSimulation
